inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

LineLength:
  Max: 100

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'